//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class BoxColliderVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<BoxCollider>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public BoxColliderVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(BoxColliderVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BoxColliderVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_BoxColliderVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public BoxColliderVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (BoxCollider element in c) {
      this.Add(element);
    }
  }

  public BoxColliderVector(global::System.Collections.Generic.IEnumerable<BoxCollider> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (BoxCollider element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public BoxCollider this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(BoxCollider[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(BoxCollider[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, BoxCollider[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public BoxCollider[] ToArray() {
    BoxCollider[] array = new BoxCollider[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<BoxCollider> global::System.Collections.Generic.IEnumerable<BoxCollider>.GetEnumerator() {
    return new BoxColliderVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new BoxColliderVectorEnumerator(this);
  }

  public BoxColliderVectorEnumerator GetEnumerator() {
    return new BoxColliderVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class BoxColliderVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<BoxCollider>
  {
    private BoxColliderVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public BoxColliderVectorEnumerator(BoxColliderVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public BoxCollider Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (BoxCollider)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    CherryEnginePINVOKE.BoxColliderVector_Clear(swigCPtr);
  }

  public void Add(BoxCollider x) {
    CherryEnginePINVOKE.BoxColliderVector_Add(swigCPtr, BoxCollider.getCPtr(x));
  }

  private uint size() {
    uint ret = CherryEnginePINVOKE.BoxColliderVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CherryEnginePINVOKE.BoxColliderVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CherryEnginePINVOKE.BoxColliderVector_reserve(swigCPtr, n);
  }

  public BoxColliderVector() : this(CherryEnginePINVOKE.new_BoxColliderVector__SWIG_0(), true) {
  }

  public BoxColliderVector(BoxColliderVector other) : this(CherryEnginePINVOKE.new_BoxColliderVector__SWIG_1(BoxColliderVector.getCPtr(other)), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public BoxColliderVector(int capacity) : this(CherryEnginePINVOKE.new_BoxColliderVector__SWIG_2(capacity), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  private BoxCollider getitemcopy(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.BoxColliderVector_getitemcopy(swigCPtr, index);
    BoxCollider ret = (cPtr == global::System.IntPtr.Zero) ? null : new BoxCollider(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private BoxCollider getitem(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.BoxColliderVector_getitem(swigCPtr, index);
    BoxCollider ret = (cPtr == global::System.IntPtr.Zero) ? null : new BoxCollider(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, BoxCollider val) {
    CherryEnginePINVOKE.BoxColliderVector_setitem(swigCPtr, index, BoxCollider.getCPtr(val));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(BoxColliderVector values) {
    CherryEnginePINVOKE.BoxColliderVector_AddRange(swigCPtr, BoxColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public BoxColliderVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.BoxColliderVector_GetRange(swigCPtr, index, count);
    BoxColliderVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new BoxColliderVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, BoxCollider x) {
    CherryEnginePINVOKE.BoxColliderVector_Insert(swigCPtr, index, BoxCollider.getCPtr(x));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, BoxColliderVector values) {
    CherryEnginePINVOKE.BoxColliderVector_InsertRange(swigCPtr, index, BoxColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CherryEnginePINVOKE.BoxColliderVector_RemoveAt(swigCPtr, index);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CherryEnginePINVOKE.BoxColliderVector_RemoveRange(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public static BoxColliderVector Repeat(BoxCollider value, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.BoxColliderVector_Repeat(BoxCollider.getCPtr(value), count);
    BoxColliderVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new BoxColliderVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CherryEnginePINVOKE.BoxColliderVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CherryEnginePINVOKE.BoxColliderVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, BoxColliderVector values) {
    CherryEnginePINVOKE.BoxColliderVector_SetRange(swigCPtr, index, BoxColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(BoxCollider value) {
    bool ret = CherryEnginePINVOKE.BoxColliderVector_Contains(swigCPtr, BoxCollider.getCPtr(value));
    return ret;
  }

  public int IndexOf(BoxCollider value) {
    int ret = CherryEnginePINVOKE.BoxColliderVector_IndexOf(swigCPtr, BoxCollider.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(BoxCollider value) {
    int ret = CherryEnginePINVOKE.BoxColliderVector_LastIndexOf(swigCPtr, BoxCollider.getCPtr(value));
    return ret;
  }

  public bool Remove(BoxCollider value) {
    bool ret = CherryEnginePINVOKE.BoxColliderVector_Remove(swigCPtr, BoxCollider.getCPtr(value));
    return ret;
  }

}

}
