//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class CameraComponent : Behaviour {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public CameraComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CherryEnginePINVOKE.CameraComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CameraComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_CameraComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CameraComponent() : this(CherryEnginePINVOKE.new_CameraComponent(), true) {
  }

  public Transform m_transform {
    set {
      CherryEnginePINVOKE.CameraComponent_m_transform_set(swigCPtr, Transform.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CherryEnginePINVOKE.CameraComponent_m_transform_get(swigCPtr);
      Transform ret = (cPtr == global::System.IntPtr.Zero) ? null : new Transform(cPtr, false);
      return ret;
    } 
  }

}

}
