//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class CapsuleCollider : Collider {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public CapsuleCollider(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CherryEnginePINVOKE.CapsuleCollider_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CapsuleCollider obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_CapsuleCollider(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CapsuleCollider() : this(CherryEnginePINVOKE.new_CapsuleCollider(), true) {
  }

  public void SetScale(float scale) {
    CherryEnginePINVOKE.CapsuleCollider_SetScale(swigCPtr, scale);
  }

  public float GetScale() {
    float ret = CherryEnginePINVOKE.CapsuleCollider_GetScale(swigCPtr);
    return ret;
  }

  public void SetRadius(float radius) {
    CherryEnginePINVOKE.CapsuleCollider_SetRadius(swigCPtr, radius);
  }

  public float GetRadius() {
    float ret = CherryEnginePINVOKE.CapsuleCollider_GetRadius(swigCPtr);
    return ret;
  }

}

}
