//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class CapsuleColliderVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<CapsuleCollider>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CapsuleColliderVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CapsuleColliderVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CapsuleColliderVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_CapsuleColliderVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CapsuleColliderVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CapsuleCollider element in c) {
      this.Add(element);
    }
  }

  public CapsuleColliderVector(global::System.Collections.Generic.IEnumerable<CapsuleCollider> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CapsuleCollider element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CapsuleCollider this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(CapsuleCollider[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(CapsuleCollider[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, CapsuleCollider[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public CapsuleCollider[] ToArray() {
    CapsuleCollider[] array = new CapsuleCollider[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<CapsuleCollider> global::System.Collections.Generic.IEnumerable<CapsuleCollider>.GetEnumerator() {
    return new CapsuleColliderVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CapsuleColliderVectorEnumerator(this);
  }

  public CapsuleColliderVectorEnumerator GetEnumerator() {
    return new CapsuleColliderVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CapsuleColliderVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<CapsuleCollider>
  {
    private CapsuleColliderVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CapsuleColliderVectorEnumerator(CapsuleColliderVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CapsuleCollider Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (CapsuleCollider)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    CherryEnginePINVOKE.CapsuleColliderVector_Clear(swigCPtr);
  }

  public void Add(CapsuleCollider x) {
    CherryEnginePINVOKE.CapsuleColliderVector_Add(swigCPtr, CapsuleCollider.getCPtr(x));
  }

  private uint size() {
    uint ret = CherryEnginePINVOKE.CapsuleColliderVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CherryEnginePINVOKE.CapsuleColliderVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CherryEnginePINVOKE.CapsuleColliderVector_reserve(swigCPtr, n);
  }

  public CapsuleColliderVector() : this(CherryEnginePINVOKE.new_CapsuleColliderVector__SWIG_0(), true) {
  }

  public CapsuleColliderVector(CapsuleColliderVector other) : this(CherryEnginePINVOKE.new_CapsuleColliderVector__SWIG_1(CapsuleColliderVector.getCPtr(other)), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CapsuleColliderVector(int capacity) : this(CherryEnginePINVOKE.new_CapsuleColliderVector__SWIG_2(capacity), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  private CapsuleCollider getitemcopy(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.CapsuleColliderVector_getitemcopy(swigCPtr, index);
    CapsuleCollider ret = (cPtr == global::System.IntPtr.Zero) ? null : new CapsuleCollider(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CapsuleCollider getitem(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.CapsuleColliderVector_getitem(swigCPtr, index);
    CapsuleCollider ret = (cPtr == global::System.IntPtr.Zero) ? null : new CapsuleCollider(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CapsuleCollider val) {
    CherryEnginePINVOKE.CapsuleColliderVector_setitem(swigCPtr, index, CapsuleCollider.getCPtr(val));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CapsuleColliderVector values) {
    CherryEnginePINVOKE.CapsuleColliderVector_AddRange(swigCPtr, CapsuleColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CapsuleColliderVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.CapsuleColliderVector_GetRange(swigCPtr, index, count);
    CapsuleColliderVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CapsuleColliderVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CapsuleCollider x) {
    CherryEnginePINVOKE.CapsuleColliderVector_Insert(swigCPtr, index, CapsuleCollider.getCPtr(x));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CapsuleColliderVector values) {
    CherryEnginePINVOKE.CapsuleColliderVector_InsertRange(swigCPtr, index, CapsuleColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CherryEnginePINVOKE.CapsuleColliderVector_RemoveAt(swigCPtr, index);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CherryEnginePINVOKE.CapsuleColliderVector_RemoveRange(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public static CapsuleColliderVector Repeat(CapsuleCollider value, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.CapsuleColliderVector_Repeat(CapsuleCollider.getCPtr(value), count);
    CapsuleColliderVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CapsuleColliderVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CherryEnginePINVOKE.CapsuleColliderVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CherryEnginePINVOKE.CapsuleColliderVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CapsuleColliderVector values) {
    CherryEnginePINVOKE.CapsuleColliderVector_SetRange(swigCPtr, index, CapsuleColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(CapsuleCollider value) {
    bool ret = CherryEnginePINVOKE.CapsuleColliderVector_Contains(swigCPtr, CapsuleCollider.getCPtr(value));
    return ret;
  }

  public int IndexOf(CapsuleCollider value) {
    int ret = CherryEnginePINVOKE.CapsuleColliderVector_IndexOf(swigCPtr, CapsuleCollider.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(CapsuleCollider value) {
    int ret = CherryEnginePINVOKE.CapsuleColliderVector_LastIndexOf(swigCPtr, CapsuleCollider.getCPtr(value));
    return ret;
  }

  public bool Remove(CapsuleCollider value) {
    bool ret = CherryEnginePINVOKE.CapsuleColliderVector_Remove(swigCPtr, CapsuleCollider.getCPtr(value));
    return ret;
  }

}

}
