//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class CherryEngine {
  public static float TAU {
    get {
      float ret = CherryEnginePINVOKE.TAU_get();
      return ret;
    } 
  }

  public static float PI {
    get {
      float ret = CherryEnginePINVOKE.PI_get();
      return ret;
    } 
  }

  public static float DEG2RAD {
    get {
      float ret = CherryEnginePINVOKE.DEG2RAD_get();
      return ret;
    } 
  }

  public static float RAD2DEG {
    get {
      float ret = CherryEnginePINVOKE.RAD2DEG_get();
      return ret;
    } 
  }

  public static float ToRadians(float angle) {
    float ret = CherryEnginePINVOKE.ToRadians(angle);
    return ret;
  }

  public static float ToDegrees(float angle) {
    float ret = CherryEnginePINVOKE.ToDegrees(angle);
    return ret;
  }

  public static float Cos(float rad) {
    float ret = CherryEnginePINVOKE.Cos(rad);
    return ret;
  }

  public static float Sin(float rad) {
    float ret = CherryEnginePINVOKE.Sin(rad);
    return ret;
  }

  public static float Tan(float rad) {
    float ret = CherryEnginePINVOKE.Tan(rad);
    return ret;
  }

  public static float Atan(float value) {
    float ret = CherryEnginePINVOKE.Atan(value);
    return ret;
  }

  public static float Abs(float value) {
    float ret = CherryEnginePINVOKE.Abs(value);
    return ret;
  }

  public static float Sqrt(float value) {
    float ret = CherryEnginePINVOKE.Sqrt(value);
    return ret;
  }

  public static bool BoolPattern(int index, uint pattern) {
    bool ret = CherryEnginePINVOKE.BoolPattern__SWIG_0(index, pattern);
    return ret;
  }

  public static bool BoolPattern(int index) {
    bool ret = CherryEnginePINVOKE.BoolPattern__SWIG_1(index);
    return ret;
  }

  public static int BoolSign(bool flag) {
    int ret = CherryEnginePINVOKE.BoolSign(flag);
    return ret;
  }

  public static float Round(double value) {
    float ret = CherryEnginePINVOKE.Round(value);
    return ret;
  }

}

}
