//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class Debug : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Debug(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Debug obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Debug() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_Debug(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static void AddLog(ELogType logType, string message, uint line, string file, string function) {
    CherryEnginePINVOKE.Debug_AddLog((int)logType, message, line, file, function);
  }

	public static void Log(ELogType type, object message,
        [System.Runtime.CompilerServices.CallerLineNumber] uint sourceLineNumber = 0u,
        [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath = "",
        [System.Runtime.CompilerServices.CallerMemberName] string memberName = "")
            => AddLog(type, message.ToString(), sourceLineNumber, sourceFilePath, memberName);

	public static void Info(object message,
        [System.Runtime.CompilerServices.CallerLineNumber] uint sourceLineNumber = 0u,
        [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath = "",
        [System.Runtime.CompilerServices.CallerMemberName] string memberName = "")
            => AddLog(ELogType.INFO, message.ToString(), sourceLineNumber, sourceFilePath, memberName);

	public static void Warning(object message,
        [System.Runtime.CompilerServices.CallerLineNumber] uint sourceLineNumber = 0u,
        [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath = "",
        [System.Runtime.CompilerServices.CallerMemberName] string memberName = "")
            => AddLog(ELogType.WARNING, message.ToString(), sourceLineNumber, sourceFilePath, memberName);

	public static void Error(object message,
        [System.Runtime.CompilerServices.CallerLineNumber] uint sourceLineNumber = 0u,
        [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath = "",
        [System.Runtime.CompilerServices.CallerMemberName] string memberName = "")
            => AddLog(ELogType.ERROR, message.ToString(), sourceLineNumber, sourceFilePath, memberName);
	
  public Debug() : this(CherryEnginePINVOKE.new_Debug(), true) {
  }

}

}
