//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public enum ETextureFormat {
  RGB = 0x80E0,
  RGBA = 0x80E1,
  DXT1 = 0x83F0,
  DXT1a = 0x83F1,
  DXT3 = 0x83F2,
  DXT5 = 0x83F3,
  DXT6 = 0x8E8E,
  DXT7 = 0x8E8C
}

}
