//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class ModelRenderer : MeshRenderer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ModelRenderer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CherryEnginePINVOKE.ModelRenderer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ModelRenderer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_ModelRenderer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void SetMeshFromPath(string meshPath) {
    CherryEnginePINVOKE.ModelRenderer_SetMeshFromPath(swigCPtr, meshPath);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetMeshPath() {
    string ret = CherryEnginePINVOKE.ModelRenderer_GetMeshPath(swigCPtr);
    return ret;
  }

  public void LoadModelFromPath(string modelPath) {
    CherryEnginePINVOKE.ModelRenderer_LoadModelFromPath(swigCPtr, modelPath);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetModelPath() {
    string ret = CherryEnginePINVOKE.ModelRenderer_GetModelPath(swigCPtr);
    return ret;
  }

}

}
