//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class PortalTeleporterComponentVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<PortalTeleporterComponent>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public PortalTeleporterComponentVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(PortalTeleporterComponentVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PortalTeleporterComponentVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_PortalTeleporterComponentVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PortalTeleporterComponentVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (PortalTeleporterComponent element in c) {
      this.Add(element);
    }
  }

  public PortalTeleporterComponentVector(global::System.Collections.Generic.IEnumerable<PortalTeleporterComponent> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (PortalTeleporterComponent element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public PortalTeleporterComponent this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(PortalTeleporterComponent[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(PortalTeleporterComponent[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, PortalTeleporterComponent[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public PortalTeleporterComponent[] ToArray() {
    PortalTeleporterComponent[] array = new PortalTeleporterComponent[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<PortalTeleporterComponent> global::System.Collections.Generic.IEnumerable<PortalTeleporterComponent>.GetEnumerator() {
    return new PortalTeleporterComponentVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new PortalTeleporterComponentVectorEnumerator(this);
  }

  public PortalTeleporterComponentVectorEnumerator GetEnumerator() {
    return new PortalTeleporterComponentVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class PortalTeleporterComponentVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<PortalTeleporterComponent>
  {
    private PortalTeleporterComponentVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public PortalTeleporterComponentVectorEnumerator(PortalTeleporterComponentVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public PortalTeleporterComponent Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (PortalTeleporterComponent)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_Clear(swigCPtr);
  }

  public void Add(PortalTeleporterComponent x) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_Add(swigCPtr, PortalTeleporterComponent.getCPtr(x));
  }

  private uint size() {
    uint ret = CherryEnginePINVOKE.PortalTeleporterComponentVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CherryEnginePINVOKE.PortalTeleporterComponentVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_reserve(swigCPtr, n);
  }

  public PortalTeleporterComponentVector() : this(CherryEnginePINVOKE.new_PortalTeleporterComponentVector__SWIG_0(), true) {
  }

  public PortalTeleporterComponentVector(PortalTeleporterComponentVector other) : this(CherryEnginePINVOKE.new_PortalTeleporterComponentVector__SWIG_1(PortalTeleporterComponentVector.getCPtr(other)), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public PortalTeleporterComponentVector(int capacity) : this(CherryEnginePINVOKE.new_PortalTeleporterComponentVector__SWIG_2(capacity), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  private PortalTeleporterComponent getitemcopy(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.PortalTeleporterComponentVector_getitemcopy(swigCPtr, index);
    PortalTeleporterComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new PortalTeleporterComponent(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private PortalTeleporterComponent getitem(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.PortalTeleporterComponentVector_getitem(swigCPtr, index);
    PortalTeleporterComponent ret = (cPtr == global::System.IntPtr.Zero) ? null : new PortalTeleporterComponent(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, PortalTeleporterComponent val) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_setitem(swigCPtr, index, PortalTeleporterComponent.getCPtr(val));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(PortalTeleporterComponentVector values) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_AddRange(swigCPtr, PortalTeleporterComponentVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public PortalTeleporterComponentVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.PortalTeleporterComponentVector_GetRange(swigCPtr, index, count);
    PortalTeleporterComponentVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new PortalTeleporterComponentVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, PortalTeleporterComponent x) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_Insert(swigCPtr, index, PortalTeleporterComponent.getCPtr(x));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, PortalTeleporterComponentVector values) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_InsertRange(swigCPtr, index, PortalTeleporterComponentVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_RemoveAt(swigCPtr, index);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_RemoveRange(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public static PortalTeleporterComponentVector Repeat(PortalTeleporterComponent value, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.PortalTeleporterComponentVector_Repeat(PortalTeleporterComponent.getCPtr(value), count);
    PortalTeleporterComponentVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new PortalTeleporterComponentVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, PortalTeleporterComponentVector values) {
    CherryEnginePINVOKE.PortalTeleporterComponentVector_SetRange(swigCPtr, index, PortalTeleporterComponentVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(PortalTeleporterComponent value) {
    bool ret = CherryEnginePINVOKE.PortalTeleporterComponentVector_Contains(swigCPtr, PortalTeleporterComponent.getCPtr(value));
    return ret;
  }

  public int IndexOf(PortalTeleporterComponent value) {
    int ret = CherryEnginePINVOKE.PortalTeleporterComponentVector_IndexOf(swigCPtr, PortalTeleporterComponent.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(PortalTeleporterComponent value) {
    int ret = CherryEnginePINVOKE.PortalTeleporterComponentVector_LastIndexOf(swigCPtr, PortalTeleporterComponent.getCPtr(value));
    return ret;
  }

  public bool Remove(PortalTeleporterComponent value) {
    bool ret = CherryEnginePINVOKE.PortalTeleporterComponentVector_Remove(swigCPtr, PortalTeleporterComponent.getCPtr(value));
    return ret;
  }

}

}
