//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class ScriptedBehaviourVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<ScriptedBehaviour>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ScriptedBehaviourVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ScriptedBehaviourVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ScriptedBehaviourVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_ScriptedBehaviourVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ScriptedBehaviourVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ScriptedBehaviour element in c) {
      this.Add(element);
    }
  }

  public ScriptedBehaviourVector(global::System.Collections.Generic.IEnumerable<ScriptedBehaviour> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ScriptedBehaviour element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ScriptedBehaviour this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ScriptedBehaviour[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ScriptedBehaviour[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ScriptedBehaviour[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public ScriptedBehaviour[] ToArray() {
    ScriptedBehaviour[] array = new ScriptedBehaviour[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<ScriptedBehaviour> global::System.Collections.Generic.IEnumerable<ScriptedBehaviour>.GetEnumerator() {
    return new ScriptedBehaviourVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new ScriptedBehaviourVectorEnumerator(this);
  }

  public ScriptedBehaviourVectorEnumerator GetEnumerator() {
    return new ScriptedBehaviourVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ScriptedBehaviourVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ScriptedBehaviour>
  {
    private ScriptedBehaviourVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ScriptedBehaviourVectorEnumerator(ScriptedBehaviourVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ScriptedBehaviour Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ScriptedBehaviour)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    CherryEnginePINVOKE.ScriptedBehaviourVector_Clear(swigCPtr);
  }

  public void Add(ScriptedBehaviour x) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_Add(swigCPtr, ScriptedBehaviour.getCPtr(x));
  }

  private uint size() {
    uint ret = CherryEnginePINVOKE.ScriptedBehaviourVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CherryEnginePINVOKE.ScriptedBehaviourVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_reserve(swigCPtr, n);
  }

  public ScriptedBehaviourVector() : this(CherryEnginePINVOKE.new_ScriptedBehaviourVector__SWIG_0(), true) {
  }

  public ScriptedBehaviourVector(ScriptedBehaviourVector other) : this(CherryEnginePINVOKE.new_ScriptedBehaviourVector__SWIG_1(ScriptedBehaviourVector.getCPtr(other)), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public ScriptedBehaviourVector(int capacity) : this(CherryEnginePINVOKE.new_ScriptedBehaviourVector__SWIG_2(capacity), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  private ScriptedBehaviour getitemcopy(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.ScriptedBehaviourVector_getitemcopy(swigCPtr, index);
    ScriptedBehaviour ret = (cPtr == global::System.IntPtr.Zero) ? null : new ScriptedBehaviour(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ScriptedBehaviour getitem(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.ScriptedBehaviourVector_getitem(swigCPtr, index);
    ScriptedBehaviour ret = (cPtr == global::System.IntPtr.Zero) ? null : new ScriptedBehaviour(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ScriptedBehaviour val) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_setitem(swigCPtr, index, ScriptedBehaviour.getCPtr(val));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(ScriptedBehaviourVector values) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_AddRange(swigCPtr, ScriptedBehaviourVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public ScriptedBehaviourVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.ScriptedBehaviourVector_GetRange(swigCPtr, index, count);
    ScriptedBehaviourVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new ScriptedBehaviourVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ScriptedBehaviour x) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_Insert(swigCPtr, index, ScriptedBehaviour.getCPtr(x));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, ScriptedBehaviourVector values) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_InsertRange(swigCPtr, index, ScriptedBehaviourVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_RemoveAt(swigCPtr, index);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_RemoveRange(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public static ScriptedBehaviourVector Repeat(ScriptedBehaviour value, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.ScriptedBehaviourVector_Repeat(ScriptedBehaviour.getCPtr(value), count);
    ScriptedBehaviourVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new ScriptedBehaviourVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CherryEnginePINVOKE.ScriptedBehaviourVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, ScriptedBehaviourVector values) {
    CherryEnginePINVOKE.ScriptedBehaviourVector_SetRange(swigCPtr, index, ScriptedBehaviourVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(ScriptedBehaviour value) {
    bool ret = CherryEnginePINVOKE.ScriptedBehaviourVector_Contains(swigCPtr, ScriptedBehaviour.getCPtr(value));
    return ret;
  }

  public int IndexOf(ScriptedBehaviour value) {
    int ret = CherryEnginePINVOKE.ScriptedBehaviourVector_IndexOf(swigCPtr, ScriptedBehaviour.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(ScriptedBehaviour value) {
    int ret = CherryEnginePINVOKE.ScriptedBehaviourVector_LastIndexOf(swigCPtr, ScriptedBehaviour.getCPtr(value));
    return ret;
  }

  public bool Remove(ScriptedBehaviour value) {
    bool ret = CherryEnginePINVOKE.ScriptedBehaviourVector_Remove(swigCPtr, ScriptedBehaviour.getCPtr(value));
    return ret;
  }

}

}
