//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class SphereColliderVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<SphereCollider>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public SphereColliderVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SphereColliderVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SphereColliderVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_SphereColliderVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SphereColliderVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SphereCollider element in c) {
      this.Add(element);
    }
  }

  public SphereColliderVector(global::System.Collections.Generic.IEnumerable<SphereCollider> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (SphereCollider element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public SphereCollider this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(SphereCollider[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(SphereCollider[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, SphereCollider[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public SphereCollider[] ToArray() {
    SphereCollider[] array = new SphereCollider[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<SphereCollider> global::System.Collections.Generic.IEnumerable<SphereCollider>.GetEnumerator() {
    return new SphereColliderVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new SphereColliderVectorEnumerator(this);
  }

  public SphereColliderVectorEnumerator GetEnumerator() {
    return new SphereColliderVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class SphereColliderVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<SphereCollider>
  {
    private SphereColliderVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public SphereColliderVectorEnumerator(SphereColliderVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public SphereCollider Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (SphereCollider)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    CherryEnginePINVOKE.SphereColliderVector_Clear(swigCPtr);
  }

  public void Add(SphereCollider x) {
    CherryEnginePINVOKE.SphereColliderVector_Add(swigCPtr, SphereCollider.getCPtr(x));
  }

  private uint size() {
    uint ret = CherryEnginePINVOKE.SphereColliderVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CherryEnginePINVOKE.SphereColliderVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CherryEnginePINVOKE.SphereColliderVector_reserve(swigCPtr, n);
  }

  public SphereColliderVector() : this(CherryEnginePINVOKE.new_SphereColliderVector__SWIG_0(), true) {
  }

  public SphereColliderVector(SphereColliderVector other) : this(CherryEnginePINVOKE.new_SphereColliderVector__SWIG_1(SphereColliderVector.getCPtr(other)), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public SphereColliderVector(int capacity) : this(CherryEnginePINVOKE.new_SphereColliderVector__SWIG_2(capacity), true) {
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  private SphereCollider getitemcopy(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.SphereColliderVector_getitemcopy(swigCPtr, index);
    SphereCollider ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphereCollider(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private SphereCollider getitem(int index) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.SphereColliderVector_getitem(swigCPtr, index);
    SphereCollider ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphereCollider(cPtr, false);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, SphereCollider val) {
    CherryEnginePINVOKE.SphereColliderVector_setitem(swigCPtr, index, SphereCollider.getCPtr(val));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(SphereColliderVector values) {
    CherryEnginePINVOKE.SphereColliderVector_AddRange(swigCPtr, SphereColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public SphereColliderVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.SphereColliderVector_GetRange(swigCPtr, index, count);
    SphereColliderVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphereColliderVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, SphereCollider x) {
    CherryEnginePINVOKE.SphereColliderVector_Insert(swigCPtr, index, SphereCollider.getCPtr(x));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, SphereColliderVector values) {
    CherryEnginePINVOKE.SphereColliderVector_InsertRange(swigCPtr, index, SphereColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CherryEnginePINVOKE.SphereColliderVector_RemoveAt(swigCPtr, index);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CherryEnginePINVOKE.SphereColliderVector_RemoveRange(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public static SphereColliderVector Repeat(SphereCollider value, int count) {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.SphereColliderVector_Repeat(SphereCollider.getCPtr(value), count);
    SphereColliderVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphereColliderVector(cPtr, true);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CherryEnginePINVOKE.SphereColliderVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CherryEnginePINVOKE.SphereColliderVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, SphereColliderVector values) {
    CherryEnginePINVOKE.SphereColliderVector_SetRange(swigCPtr, index, SphereColliderVector.getCPtr(values));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(SphereCollider value) {
    bool ret = CherryEnginePINVOKE.SphereColliderVector_Contains(swigCPtr, SphereCollider.getCPtr(value));
    return ret;
  }

  public int IndexOf(SphereCollider value) {
    int ret = CherryEnginePINVOKE.SphereColliderVector_IndexOf(swigCPtr, SphereCollider.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(SphereCollider value) {
    int ret = CherryEnginePINVOKE.SphereColliderVector_LastIndexOf(swigCPtr, SphereCollider.getCPtr(value));
    return ret;
  }

  public bool Remove(SphereCollider value) {
    bool ret = CherryEnginePINVOKE.SphereColliderVector_Remove(swigCPtr, SphereCollider.getCPtr(value));
    return ret;
  }

}

}
