//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class Time : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Time(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Time obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Time() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_Time(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static float GetDeltaTime() {
    float ret = CherryEnginePINVOKE.Time_GetDeltaTime();
    return ret;
  }

  public static float GetTimeScale() {
    float ret = CherryEnginePINVOKE.Time_GetTimeScale();
    return ret;
  }

  public static float GetFixedDeltaTime() {
    float ret = CherryEnginePINVOKE.Time_GetFixedDeltaTime();
    return ret;
  }

  public static double GetElapsedTime() {
    double ret = CherryEnginePINVOKE.Time_GetElapsedTime();
    return ret;
  }

  public static void SetTimeScale(float newTime) {
    CherryEnginePINVOKE.Time_SetTimeScale(newTime);
  }

  public static void SetFixedDeltaTime(float newTime) {
    CherryEnginePINVOKE.Time_SetFixedDeltaTime(newTime);
  }

}

}
