//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CCEngine {

public class Transform : Behaviour {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public Transform(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CherryEnginePINVOKE.Transform_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Transform obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CherryEnginePINVOKE.delete_Transform(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void SetPosition(Vector3 position) {
    CherryEnginePINVOKE.Transform_SetPosition(swigCPtr, Vector3.getCPtr(position));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlobalPosition(Vector3 position) {
    CherryEnginePINVOKE.Transform_SetGlobalPosition(swigCPtr, Vector3.getCPtr(position));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetPosition() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_GetPosition(swigCPtr), true);
    return ret;
  }

  public Vector3 GetGlobalPosition() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_GetGlobalPosition(swigCPtr), true);
    return ret;
  }

  public void SetEuler(Vector3 rotation) {
    CherryEnginePINVOKE.Transform_SetEuler(swigCPtr, Vector3.getCPtr(rotation));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRotation(Quaternion rotation) {
    CherryEnginePINVOKE.Transform_SetRotation(swigCPtr, Quaternion.getCPtr(rotation));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlobalRotation(Vector3 rotation) {
    CherryEnginePINVOKE.Transform_SetGlobalRotation__SWIG_0(swigCPtr, Vector3.getCPtr(rotation));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlobalRotation(Quaternion rotation) {
    CherryEnginePINVOKE.Transform_SetGlobalRotation__SWIG_1(swigCPtr, Quaternion.getCPtr(rotation));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetEuler() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_GetEuler(swigCPtr), true);
    return ret;
  }

  public Quaternion GetRotation() {
    Quaternion ret = new Quaternion(CherryEnginePINVOKE.Transform_GetRotation(swigCPtr), true);
    return ret;
  }

  public Quaternion GetGlobalRotation() {
    Quaternion ret = new Quaternion(CherryEnginePINVOKE.Transform_GetGlobalRotation(swigCPtr), true);
    return ret;
  }

  public void SetScale(Vector3 scale) {
    CherryEnginePINVOKE.Transform_SetScale(swigCPtr, Vector3.getCPtr(scale));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlobalScale(Vector3 scale) {
    CherryEnginePINVOKE.Transform_SetGlobalScale(swigCPtr, Vector3.getCPtr(scale));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetScale() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_GetScale(swigCPtr), true);
    return ret;
  }

  public Vector3 GetGlobalScale() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_GetGlobalScale(swigCPtr), true);
    return ret;
  }

  public void Translate(Vector3 translation) {
    CherryEnginePINVOKE.Transform_Translate(swigCPtr, Vector3.getCPtr(translation));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Rotate(Vector3 eulerAngles) {
    CherryEnginePINVOKE.Transform_Rotate__SWIG_0(swigCPtr, Vector3.getCPtr(eulerAngles));
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Rotate(Vector3 axis, float angle) {
    CherryEnginePINVOKE.Transform_Rotate__SWIG_1(swigCPtr, Vector3.getCPtr(axis), angle);
    if (CherryEnginePINVOKE.SWIGPendingException.Pending) throw CherryEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 Up() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_Up(swigCPtr), true);
    return ret;
  }

  public Vector3 Right() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_Right(swigCPtr), true);
    return ret;
  }

  public Vector3 Forward() {
    Vector3 ret = new Vector3(CherryEnginePINVOKE.Transform_Forward(swigCPtr), true);
    return ret;
  }

  public bool IsRoot() {
    bool ret = CherryEnginePINVOKE.Transform_IsRoot(swigCPtr);
    return ret;
  }

  public void SetParent(Transform parent, bool reapplyPosition, bool reapplyRot, bool reapplyScale) {
    CherryEnginePINVOKE.Transform_SetParent__SWIG_0(swigCPtr, Transform.getCPtr(parent), reapplyPosition, reapplyRot, reapplyScale);
  }

  public void SetParent(Transform parent, bool reapplyPosition, bool reapplyRot) {
    CherryEnginePINVOKE.Transform_SetParent__SWIG_1(swigCPtr, Transform.getCPtr(parent), reapplyPosition, reapplyRot);
  }

  public void SetParent(Transform parent, bool reapplyPosition) {
    CherryEnginePINVOKE.Transform_SetParent__SWIG_2(swigCPtr, Transform.getCPtr(parent), reapplyPosition);
  }

  public void SetParent(Transform parent) {
    CherryEnginePINVOKE.Transform_SetParent__SWIG_3(swigCPtr, Transform.getCPtr(parent));
  }

  public Transform GetParent() {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.Transform_GetParent(swigCPtr);
    Transform ret = (cPtr == global::System.IntPtr.Zero) ? null : new Transform(cPtr, false);
    return ret;
  }

  public Transform GetRootParent() {
    global::System.IntPtr cPtr = CherryEnginePINVOKE.Transform_GetRootParent(swigCPtr);
    Transform ret = (cPtr == global::System.IntPtr.Zero) ? null : new Transform(cPtr, false);
    return ret;
  }

		public Vector3 position { get => GetPosition(); set => SetPosition(value); }
		public Vector3 eulerAngles { get => GetEuler(); set => SetEuler(value); }
		public Quaternion rotation { get => GetRotation(); set => SetRotation(value); }
		public Vector3 scale { get => GetScale(); set => SetScale(value); }
	
}

}
