/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_CherryEngine_WRAP_H_
#define SWIG_CherryEngine_WRAP_H_

class SwigDirector_Behaviour : public Behaviour, public Swig::Director {

public:
    SwigDirector_Behaviour();
    virtual ~SwigDirector_Behaviour();
    void swig_connect_director();
    void swig_init_callbacks();
};


#endif
